config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/astalosj/sqaaas-try:
      branch: master
      repo: https://github.com/astalosj/sqaaas-try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-pear-chin.sh
        container: qc.acc_woozy-rust-snake
  QC.Doc:
    repos:
      github.com/astalosj/sqaaas-try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-peach-fousek.sh
        container: qc.doc_cheeky-xanthic-robin
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-turquoise-warthog.sh
        container: qc.doc_messy-mauve-worm
      github.com/astalosj/sqaaas-try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-myrtle-termite.sh
        container: qc.doc_thirsty-cornflower-duck
      github.com/astalosj/sqaaas-try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-auburn-dachsbracke.sh
        container: qc.doc_lousy-saffron-cat
  QC.Lic:
    repos:
      github.com/astalosj/sqaaas-try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-pear-yak.sh
        container: qc.lic_thirsty-pear-frise
  QC.Met:
    repos:
      github.com/astalosj/sqaaas-try validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-emerald-coyote.sh
        container: qc.met_chewy-auburn-jellyfish
  QC.Sec:
    repos:
      github.com/astalosj/sqaaas-try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-aqua-frog.sh
        container: qc.sec_stinky-fuchsia-oriole
  QC.Sty:
    repos:
      github.com/astalosj/sqaaas-try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-grey-barnacle.sh
        container: qc.sty_snoopy-emerald-cow
      github.com/astalosj/sqaaas-try jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-malachite-squirrel.sh
        container: qc.sty_sleepy-celadon-hornet
  QC.Ver:
    repos:
      github.com/astalosj/sqaaas-try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-zucchini-ostrich.sh
        container: qc.ver_snoopy-puce-vulture
timeout: 1800
