config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/astalosj/sqaaas-try:
      branch: master
      repo: https://github.com/astalosj/sqaaas-try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-sepia-husky.sh
        container: qc.acc_crabby-orchid-barnacle
  QC.Doc:
    repos:
      github.com/astalosj/sqaaas-try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-vermilion-corgi.sh
        container: qc.doc_whiny-amber-mastiff
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-tan-coral.sh
        container: qc.doc_gimpy-magenta-starfish
      github.com/astalosj/sqaaas-try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-ivory-rottweiler.sh
        container: qc.doc_craggy-olivine-wolf
      github.com/astalosj/sqaaas-try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-jade-barnacle.sh
        container: qc.doc_lumpy-vermilion-dodo
  QC.Lic:
    repos:
      github.com/astalosj/sqaaas-try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.messy-harlequin-kingfisher.sh
        container: qc.lic_flabby-platinum-iguana
  QC.Sec:
    repos:
      github.com/astalosj/sqaaas-try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-puce-buffalo.sh
        container: qc.sec_flaky-taupe-uguisu
  QC.Sty:
    repos:
      github.com/astalosj/sqaaas-try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-indigo-eel.sh
        container: qc.sty_snappy-amethyst-beagle
  QC.Ver:
    repos:
      github.com/astalosj/sqaaas-try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-aquamarine-fish.sh
        container: qc.ver_gloppy-mauve-dane
timeout: 1800
