config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/astalosj/sqaaas-try:
      branch: master
      repo: https://github.com/astalosj/sqaaas-try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-amaranth-zebra.sh
        container: qc.acc_sunny-mauve-eagle
  QC.Doc:
    repos:
      github.com/astalosj/sqaaas-try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-yellow-salamander.sh
        container: qc.doc_skimpy-xanthic-tarantula
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-corn-slug.sh
        container: qc.doc_lovely-cerise-fish
      github.com/astalosj/sqaaas-try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-alizarin-akita.sh
        container: qc.doc_stinky-ochre-dog
      github.com/astalosj/sqaaas-try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-cerise-snake.sh
        container: qc.doc_snazzy-orchid-labradoodle
  QC.Lic:
    repos:
      github.com/astalosj/sqaaas-try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-dandelion-gar.sh
        container: qc.lic_baggy-tan-worm
  QC.Sec:
    repos:
      github.com/astalosj/sqaaas-try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-myrtle-quetzal.sh
        container: qc.sec_gamy-cerulean-ocelot
  QC.Sty:
    repos:
      github.com/astalosj/sqaaas-try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-salmon-audemer.sh
        container: qc.sty_scanty-charcoal-axolotl
  QC.Ver:
    repos:
      github.com/astalosj/sqaaas-try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-firebrick-snail.sh
        container: qc.ver_scanty-brown-drever
timeout: 1800
