config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/astalosj/sqaaas-try:
      branch: master
      repo: https://github.com/astalosj/sqaaas-try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-sangria-vole.sh
        container: qc.acc_goopy-charcoal-mongrel
  QC.Doc:
    repos:
      github.com/astalosj/sqaaas-try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-amethyst-budgerigar.sh
        container: qc.doc_flimsy-asparagus-retriever
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-apricot-capybara.sh
        container: qc.doc_crabby-mauve-starfish
      github.com/astalosj/sqaaas-try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-beige-monkey.sh
        container: qc.doc_crabby-cobalt-monster
      github.com/astalosj/sqaaas-try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-puce-neanderthal.sh
        container: qc.doc_wheezy-scarlet-bat
  QC.Lic:
    repos:
      github.com/astalosj/sqaaas-try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-peach-maltese.sh
        container: qc.lic_jumpy-teal-echidna
  QC.Met:
    repos:
      github.com/astalosj/sqaaas-try validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-maroon-caiman.sh
        container: qc.met_snoopy-cinnamon-neanderthal
  QC.Sec:
    repos:
      github.com/astalosj/sqaaas-try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-beige-eleuth.sh
        container: qc.sec_gamy-auburn-blue
  QC.Sty:
    repos:
      github.com/astalosj/sqaaas-try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-mustard-earwig.sh
        container: qc.sty_sickly-wisteria-molly
      github.com/astalosj/sqaaas-try jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-myrtle-starfish.sh
        container: qc.sty_bluesy-orchid-tzu
  QC.Ver:
    repos:
      github.com/astalosj/sqaaas-try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-maroon-tzu.sh
        container: qc.ver_crappy-russet-chin
timeout: 1800
