config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/astalosj/sqaaas-try:
      branch: master
      repo: https://github.com/astalosj/sqaaas-try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-russet-badger.sh
        container: qc.acc_homey-beige-mongoose
  QC.Doc:
    repos:
      github.com/astalosj/sqaaas-try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-thistle-newt.sh
        container: qc.doc_tacky-goldenrod-spider
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-purple-dingo.sh
        container: qc.doc_geeky-teal-sparrow
      github.com/astalosj/sqaaas-try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-white-robin.sh
        container: qc.doc_queasy-green-terrier
      github.com/astalosj/sqaaas-try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-gamboge-buffalo.sh
        container: qc.doc_zippy-pumpkin-angelfish
  QC.Lic:
    repos:
      github.com/astalosj/sqaaas-try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-taupe-duck.sh
        container: qc.lic_skanky-purple-numbat
  QC.Sec:
    repos:
      github.com/astalosj/sqaaas-try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homely-amber-javanese.sh
        container: qc.sec_woozy-tan-sheep
  QC.Sty:
    repos:
      github.com/astalosj/sqaaas-try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-blue-grouse.sh
        container: qc.sty_gimpy-razzmatazz-albatross
  QC.Ver:
    repos:
      github.com/astalosj/sqaaas-try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-carmine-panda.sh
        container: qc.ver_goopy-sapphire-buffalo
timeout: 1800
