config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/astalosj/sqaaas-try:
      branch: master
      repo: https://github.com/astalosj/sqaaas-try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-sepia-snail.sh
        container: qc.acc_shabby-tangerine-harrier
  QC.Doc:
    repos:
      github.com/astalosj/sqaaas-try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-thistle-bombay.sh
        container: qc.doc_pretty-orchid-albatross
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-magnolia-chihuahua.sh
        container: qc.doc_sleazy-ecru-bloodhound
      github.com/astalosj/sqaaas-try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-fuchsia-anteater.sh
        container: qc.doc_foggy-thistle-budgerigar
      github.com/astalosj/sqaaas-try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-aquamarine-deer.sh
        container: qc.doc_woolly-zucchini-eleuth
  QC.Lic:
    repos:
      github.com/astalosj/sqaaas-try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-tangerine-llama.sh
        container: qc.lic_skimpy-olive-kangaroo
  QC.Sec:
    repos:
      github.com/astalosj/sqaaas-try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homely-chestnut-seahorse.sh
        container: qc.sec_bluesy-chartreuse-spoonbill
  QC.Sty:
    repos:
      github.com/astalosj/sqaaas-try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-orange-crab.sh
        container: qc.sty_hasty-firebrick-squid
  QC.Ver:
    repos:
      github.com/astalosj/sqaaas-try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-aqua-vulture.sh
        container: qc.ver_thirsty-orchid-mayfly
timeout: 1800
