config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/astalosj/sqaaas-try:
      branch: master
      repo: https://github.com/astalosj/sqaaas-try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-celadon-chihuahua.sh
        container: qc.acc_foggy-eggplant-leopard
  QC.Doc:
    repos:
      github.com/astalosj/sqaaas-try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-seashell-barracuda.sh
        container: qc.doc_greasy-puce-sloth
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-dandelion-gharial.sh
        container: qc.doc_zippy-cornflower-owl
      github.com/astalosj/sqaaas-try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-ivory-dingo.sh
        container: qc.doc_foggy-salmon-tetra
      github.com/astalosj/sqaaas-try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-pumpkin-deer.sh
        container: qc.doc_scaly-persimmon-elephant
  QC.Lic:
    repos:
      github.com/astalosj/sqaaas-try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-maroon-mau.sh
        container: qc.lic_seedy-goldenrod-owl
  QC.Met:
    repos:
      github.com/astalosj/sqaaas-try validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-razzmatazz-sloth.sh
        container: qc.met_lanky-cerulean-moth
  QC.Sec:
    repos:
      github.com/astalosj/sqaaas-try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.surly-heliotrope-sheepdog.sh
        container: qc.sec_wimpy-peach-cockroach
  QC.Sty:
    repos:
      github.com/astalosj/sqaaas-try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-amaranth-chihuahua.sh
        container: qc.sty_ugly-lime-lemur
      github.com/astalosj/sqaaas-try jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-indigo-tamarin.sh
        container: qc.sty_craggy-grey-newt
  QC.Ver:
    repos:
      github.com/astalosj/sqaaas-try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-dandelion-bobcat.sh
        container: qc.ver_cloudy-cerulean-abyssinian
timeout: 1800
