config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/astalosj/sqaaas-try:
      branch: master
      repo: https://github.com/astalosj/sqaaas-try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-burgundy-whale.sh
        container: qc.acc_bumpy-lemon-giraffe
  QC.Doc:
    repos:
      github.com/astalosj/sqaaas-try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-magnolia-serval.sh
        container: qc.doc_squirrely-brown-cat
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-ultramarine-tzu.sh
        container: qc.doc_woozy-lime-fox
      github.com/astalosj/sqaaas-try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-cerulean-capuchin.sh
        container: qc.doc_leaky-indigo-ostrich
      github.com/astalosj/sqaaas-try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-scarlet-blue.sh
        container: qc.doc_greasy-buff-ladybird
  QC.Lic:
    repos:
      github.com/astalosj/sqaaas-try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-teal-squirt.sh
        container: qc.lic_clammy-lavender-pinscher
  QC.Sec:
    repos:
      github.com/astalosj/sqaaas-try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-viridian-russel.sh
        container: qc.sec_sunny-chestnut-robin
  QC.Sty:
    repos:
      github.com/astalosj/sqaaas-try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-scarlet-rottweiler.sh
        container: qc.sty_baggy-violet-butterfly
  QC.Ver:
    repos:
      github.com/astalosj/sqaaas-try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-salmon-ibis.sh
        container: qc.ver_wiggy-ruby-barracuda
timeout: 1800
