config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/astalosj/sqaaas-try:
      branch: master
      repo: https://github.com/astalosj/sqaaas-try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-apricot-spider.sh
        container: qc.acc_hazy-alizarin-earwig
  QC.Doc:
    repos:
      github.com/astalosj/sqaaas-try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-magnolia-spider.sh
        container: qc.doc_skinny-charcoal-lynx
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-cerise-falcon.sh
        container: qc.doc_gimpy-viridian-gharial
      github.com/astalosj/sqaaas-try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-harlequin-harrier.sh
        container: qc.doc_zippy-teal-ocelot
      github.com/astalosj/sqaaas-try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-scarlet-eleuth.sh
        container: qc.doc_queasy-rust-kangaroo
  QC.Lic:
    repos:
      github.com/astalosj/sqaaas-try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-pumpkin-hamster.sh
        container: qc.lic_woozy-ivory-discus
  QC.Met:
    repos:
      github.com/astalosj/sqaaas-try validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-auburn-eagle.sh
        container: qc.met_paltry-cardinal-ray
  QC.Sec:
    repos:
      github.com/astalosj/sqaaas-try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-orchid-dog.sh
        container: qc.sec_greasy-aquamarine-grasshopper
  QC.Sty:
    repos:
      github.com/astalosj/sqaaas-try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-white-cougar.sh
        container: qc.sty_lovely-corn-gar
      github.com/astalosj/sqaaas-try jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-chocolate-uguisu.sh
        container: qc.sty_paltry-zucchini-ragdoll
  QC.Ver:
    repos:
      github.com/astalosj/sqaaas-try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-amaranth-koala.sh
        container: qc.ver_trippy-ochre-liger
timeout: 1800
