config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/astalosj/sqaaas-try:
      branch: master
      repo: https://github.com/astalosj/sqaaas-try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-linen-lizard.sh
        container: qc.acc_wheezy-plum-chihuahua
  QC.Doc:
    repos:
      github.com/astalosj/sqaaas-try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-silver-neanderthal.sh
        container: qc.doc_sunny-indigo-eagle
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-tomato-okapi.sh
        container: qc.doc_sunny-amaranth-spoonbill
      github.com/astalosj/sqaaas-try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-firebrick-dog.sh
        container: qc.doc_scummy-xanthic-angora
      github.com/astalosj/sqaaas-try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-vermilion-kingfisher.sh
        container: qc.doc_flimsy-cerise-eagle
  QC.Lic:
    repos:
      github.com/astalosj/sqaaas-try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-wisteria-wrasse.sh
        container: qc.lic_pokey-blue-heron
  QC.Met:
    repos:
      github.com/astalosj/sqaaas-try validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-lilac-buffalo.sh
        container: qc.met_clammy-plum-coral
  QC.Sec:
    repos:
      github.com/astalosj/sqaaas-try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-peach-worm.sh
        container: qc.sec_hilly-chartreuse-caterpillar
  QC.Sty:
    repos:
      github.com/astalosj/sqaaas-try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-magnolia-skunk.sh
        container: qc.sty_paltry-turquoise-chameleon
      github.com/astalosj/sqaaas-try jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-indigo-rottweiler.sh
        container: qc.sty_woozy-gold-serval
  QC.Ver:
    repos:
      github.com/astalosj/sqaaas-try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-teal-tarsier.sh
        container: qc.ver_gloppy-saffron-wolfhound
timeout: 1800
