config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/astalosj/sqaaas-try:
      branch: master
      repo: https://github.com/astalosj/sqaaas-try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-khaki-olm.sh
        container: qc.acc_skimpy-amaranth-bobcat
  QC.Doc:
    repos:
      github.com/astalosj/sqaaas-try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-zucchini-maltese.sh
        container: qc.doc_wiggy-flax-chameleon
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-buff-balinese.sh
        container: qc.doc_zippy-plum-angelfish
      github.com/astalosj/sqaaas-try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-azure-retriever.sh
        container: qc.doc_gummy-denim-buzzard
      github.com/astalosj/sqaaas-try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-pink-hyena.sh
        container: qc.doc_sunny-cream-dodo
  QC.Lic:
    repos:
      github.com/astalosj/sqaaas-try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-cardinal-affenpinscher.sh
        container: qc.lic_leaky-maroon-albatross
  QC.Met:
    repos:
      github.com/astalosj/sqaaas-try validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-grey-oriole.sh
        container: qc.met_muzzy-beige-squid
  QC.Sec:
    repos:
      github.com/astalosj/sqaaas-try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-plum-neanderthal.sh
        container: qc.sec_sickly-periwinkle-fox
  QC.Sty:
    repos:
      github.com/astalosj/sqaaas-try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-emerald-dane.sh
        container: qc.sty_chewy-indigo-mule
      github.com/astalosj/sqaaas-try jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-cerulean-lemming.sh
        container: qc.sty_skinny-jade-collie
  QC.Ver:
    repos:
      github.com/astalosj/sqaaas-try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-zucchini-newt.sh
        container: qc.ver_shabby-blue-penguin
timeout: 1800
