config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/astalosj/sqaaas-try:
      branch: master
      repo: https://github.com/astalosj/sqaaas-try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-lilac-zebu.sh
        container: qc.acc_tacky-sangria-crocodile
  QC.Doc:
    repos:
      github.com/astalosj/sqaaas-try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-sepia-fossa.sh
        container: qc.doc_blurry-cerise-dunker
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-grey-hummingbird.sh
        container: qc.doc_gummy-sapphire-dragon
      github.com/astalosj/sqaaas-try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-thistle-mongrel.sh
        container: qc.doc_randy-brass-mongrel
      github.com/astalosj/sqaaas-try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-silver-armadillo.sh
        container: qc.doc_muzzy-ochre-collie
  QC.Lic:
    repos:
      github.com/astalosj/sqaaas-try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-chestnut-quetzal.sh
        container: qc.lic_silly-cinnabar-whippet
  QC.Met:
    repos:
      github.com/astalosj/sqaaas-try validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-firebrick-chow.sh
        container: qc.met_lumpy-azure-foxhound
  QC.Sec:
    repos:
      github.com/astalosj/sqaaas-try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ready-asparagus-mau.sh
        container: qc.sec_beady-ivory-balinese
  QC.Sty:
    repos:
      github.com/astalosj/sqaaas-try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-chocolate-moth.sh
        container: qc.sty_crabby-orchid-newfoundland
      github.com/astalosj/sqaaas-try jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-orange-horse.sh
        container: qc.sty_geeky-fuchsia-fossa
  QC.Ver:
    repos:
      github.com/astalosj/sqaaas-try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-cobalt-peccary.sh
        container: qc.ver_snappy-lime-oyster
timeout: 1800
