config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/astalosj/sqaaas-try:
      branch: master
      repo: https://github.com/astalosj/sqaaas-try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-salmon-gar.sh
        container: qc.acc_goopy-teal-zebra
  QC.Doc:
    repos:
      github.com/astalosj/sqaaas-try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-mauve-camel.sh
        container: qc.doc_gummy-goldenrod-mouse
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-azure-penguin.sh
        container: qc.doc_cozy-cardinal-owl
      github.com/astalosj/sqaaas-try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-olivine-spaniel.sh
        container: qc.doc_snappy-tomato-lynx
      github.com/astalosj/sqaaas-try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-periwinkle-gecko.sh
        container: qc.doc_paltry-seashell-stoat
  QC.Lic:
    repos:
      github.com/astalosj/sqaaas-try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-goldenrod-ocelot.sh
        container: qc.lic_pasty-buff-stoat
  QC.Met:
    repos:
      github.com/astalosj/sqaaas-try validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-vermilion-drever.sh
        container: qc.met_crabby-puce-beagle
  QC.Sec:
    repos:
      github.com/astalosj/sqaaas-try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-white-caiman.sh
        container: qc.sec_lanky-tan-falcon
  QC.Sty:
    repos:
      github.com/astalosj/sqaaas-try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-salmon-cuttlefish.sh
        container: qc.sty_hasty-scarlet-cockroach
      github.com/astalosj/sqaaas-try jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-rust-beaver.sh
        container: qc.sty_baggy-mauve-wasp
  QC.Ver:
    repos:
      github.com/astalosj/sqaaas-try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-rose-worm.sh
        container: qc.ver_thirsty-cinnabar-magpie
timeout: 1800
