config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/astalosj/sqaaas-try:
      branch: master
      repo: https://github.com/astalosj/sqaaas-try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-brown-spider.sh
        container: qc.acc_queasy-mauve-javanese
  QC.Doc:
    repos:
      github.com/astalosj/sqaaas-try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-mauve-ladybird.sh
        container: qc.doc_blurry-yellow-buzzard
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-emerald-avocet.sh
        container: qc.doc_sleepy-turquoise-kingfisher
      github.com/astalosj/sqaaas-try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-cornflower-terrier.sh
        container: qc.doc_stealthy-cornflower-toucan
      github.com/astalosj/sqaaas-try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-lime-ibis.sh
        container: qc.doc_goopy-orange-wolf
  QC.Lic:
    repos:
      github.com/astalosj/sqaaas-try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-thistle-hamster.sh
        container: qc.lic_fuzzy-azure-gopher
  QC.Sec:
    repos:
      github.com/astalosj/sqaaas-try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-corn-owl.sh
        container: qc.sec_pasty-fuchsia-quoll
  QC.Sty:
    repos:
      github.com/astalosj/sqaaas-try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-brass-chameleon.sh
        container: qc.sty_nippy-cyan-schnauzer
  QC.Ver:
    repos:
      github.com/astalosj/sqaaas-try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-scarlet-dachshund.sh
        container: qc.ver_skimpy-fuchsia-zonkey
timeout: 1800
