config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/astalosj/sqaaas-try:
      branch: master
      repo: https://github.com/astalosj/sqaaas-try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-lemon-lion.sh
        container: qc.acc_crappy-seashell-greyhound
  QC.Doc:
    repos:
      github.com/astalosj/sqaaas-try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-pear-hummingbird.sh
        container: qc.doc_hilly-gold-bullfrog
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-sepia-sparrow.sh
        container: qc.doc_pokey-cerulean-hornet
      github.com/astalosj/sqaaas-try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-cream-bonobo.sh
        container: qc.doc_snoopy-rust-snake
      github.com/astalosj/sqaaas-try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-magenta-alligator.sh
        container: qc.doc_shaggy-chocolate-meerkat
  QC.Lic:
    repos:
      github.com/astalosj/sqaaas-try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-gold-hummingbird.sh
        container: qc.lic_gummy-lilac-nightingale
  QC.Sec:
    repos:
      github.com/astalosj/sqaaas-try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-flax-ladybird.sh
        container: qc.sec_boozy-cornflower-octopus
  QC.Sty:
    repos:
      github.com/astalosj/sqaaas-try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-burgundy-lobster.sh
        container: qc.sty_thirsty-wheat-snail
  QC.Ver:
    repos:
      github.com/astalosj/sqaaas-try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-malachite-vole.sh
        container: qc.ver_messy-blue-kiwi
timeout: 1800
