config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/astalosj/sqaaas-try:
      branch: master
      repo: https://github.com/astalosj/sqaaas-try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-khaki-seal.sh
        container: qc.acc_geeky-ultramarine-hare
  QC.Doc:
    repos:
      github.com/astalosj/sqaaas-try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-bronze-mammoth.sh
        container: qc.doc_gloppy-beige-crab
      github.com/astalosj/sqaaas-try git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-rust-argentino.sh
        container: qc.doc_skimpy-charcoal-gecko
      github.com/astalosj/sqaaas-try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-gold-llama.sh
        container: qc.doc_dorky-rust-coati
      github.com/astalosj/sqaaas-try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-crimson-squirrel.sh
        container: qc.doc_lovely-carmine-havanese
  QC.Lic:
    repos:
      github.com/astalosj/sqaaas-try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-linen-fousek.sh
        container: qc.lic_pokey-pumpkin-walrus
  QC.Sec:
    repos:
      github.com/astalosj/sqaaas-try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-peach-sponge.sh
        container: qc.sec_fuzzy-red-numbat
  QC.Sty:
    repos:
      github.com/astalosj/sqaaas-try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-lilac-hamster.sh
        container: qc.sty_blurry-razzmatazz-warthog
  QC.Ver:
    repos:
      github.com/astalosj/sqaaas-try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-orange-flamingo.sh
        container: qc.ver_chewy-puce-warthog
timeout: 1800
